---
- name: Run Command "show configuration | display json"
  junos_command:
    commands: show configuration
    format: json
  register: result

- name: Get Device Config
  set_fact:
    device_config: "{{ result.stdout[0].configuration }}"
